apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  virtualhost.conf: |
    upstream app {
      server localhost:80;
    }
    server {
      listen 8080;
      location / {
        proxy_pass http://app;
      }
    }