apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-task
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-task
  template:
    metadata:
      labels:
        app: docker-task
    spec:
      containers:
        - name: docker-task
          image: erbidium/docker-task:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health-check
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 2
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          resources:
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: /etc/nginx
            readOnly: true
            name: nginx-conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: virtualhost.conf
                path: virtualhost/virtualhost.conf
