name: Code Analysis
on:
  push:
    branches: [ ci-cd-task ]
  pull_request:
    branches: [ ci-cd-task ]
jobs:
  analyze_application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install packages
        run: |
          npm ci
      - name: Eslint and Prettier checks
        run: |
          npm run lint:check
          npm run format:check
